# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedBy', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('favorite', models.ManyToManyField(related_name='fave', to='login_app.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login_app.User')),
            ],
        ),
    ]
