# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_auto_20170728_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='content',
        ),
    ]
