# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_remove_quote_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorite',
        ),
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.CharField(default='This is a quote.', max_length=1000),
            preserve_default=False,
        ),
    ]
