# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('quotes_app', '0005_auto_20170728_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fave', to='login_app.User'),
            preserve_default=False,
        ),
    ]
