# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0006_quote_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fave', to='login_app.User'),
        ),
    ]
